name: Oak CI (Ubuntu)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-12 g++-12 \
            libgmp3-dev \
            ninja-build \
            python3-venv

      - name: Set GCC 12 as default
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: 0.16.0

      - name: Build libpkmn
        run: |
          chmod +x dev/libpkmn
          ./dev/libpkmn

      - name: Build Oak (CMake + install Python binaries)
        run: |
          chmod +x dev/release
          ./dev/release
          chmod +x dev/debug
          ./dev/debug

      - name: Build, repair, install, and test wheel
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip build auditwheel
          python -m build
          auditwheel repair dist/*.whl \
            --exclude 'search-test' \
            --exclude 'generate' \
            --exclude 'vs' \
            --exclude 'chall' \
            --exclude 'benchmark' \
            --wheel-dir dist/repaired
          pip install dist/repaired/*.whl
          oak-search-test

      - name: Upload built wheel
        uses: actions/upload-artifact@v4
        with:
          name: oak-lab-wheel-ubuntu22-py${{ matrix.python-version }}
          path: dist/repaired/*.whl
          if-no-files-found: error